import { COST_HEADS, YEARS, aggregate, tracked, delta, type Amount, type BudgetField } from '@/data/md-plan';
import { inr } from '@/data/md-scenario';
import { usePlan } from './PlanContext';
import { ContextInfo, Panel, Table } from './Shared';
export const money=(v:Amount)=>v===null?'Not loaded':inr(v);
export const variance=(v:Amount)=>v===null?'Not loaded':`${v>0?'+':''}${inr(v)}`;
export function NumberInput({label,value,onChange}:{label:string;value:Amount;onChange:(v:Amount)=>void}) {return <input className="mc-number-input" aria-label={label} type="number" min="0" step="0.01" placeholder="Not loaded" value={value??''} onChange={e=>{const n=e.target.value===''?null:Number(e.target.value);if(n===null||Number.isFinite(n)&&n>=0)onChange(n);}}/>;}
export function BudgetTable({ids,title='Budget tracking'}:{ids:string[];title?:string}){
 const {year,state,setTracking}=usePlan();const i=YEARS.indexOf(year);const rows=COST_HEADS.filter(h=>ids.includes(h.id));
 return <Panel title={title} context="Actual = spending to date. Committed = unpaid obligations. Full-year forecast includes actual, commitments and remaining expected spending; these columns are not added together. A total stays “Not loaded” until every included head is entered. Enter 0 for a confirmed zero. People and Culture and JSW entries use the same records shown in Finance." aside={<span>{year} · INR crore</span>}><Table headers={['Budget head / owner','Annual budget','YTD budget','YTD actual','Committed','FY forecast','FY variance']}>{rows.map(h=><tr key={h.id}><th scope="row">{h.name}<ContextInfo>{h.owner}</ContextInfo></th><td>{inr(h.values[i])}</td>{(['ytdBudget','actual','committed','forecast'] as BudgetField[]).map(field=><td key={field}><NumberInput label={`${h.name} ${field}`} value={tracked(state.tracking,year,h.id,field)} onChange={v=>setTracking(h.id,field,v)}/></td>)}<td className={(delta(tracked(state.tracking,year,h.id,'forecast'),h.values[i])??0)>0?'mc-red':''}>{variance(delta(tracked(state.tracking,year,h.id,'forecast'),h.values[i]))}</td></tr>)}<tr className="mc-total-row"><th>Total</th><td>{inr(rows.reduce((s,h)=>s+h.values[i],0))}</td>{(['ytdBudget','actual','committed','forecast'] as BudgetField[]).map(f=><td key={f}>{money(aggregate(state.tracking,year,ids,f))}</td>)}<td>{variance(delta(aggregate(state.tracking,year,ids,'forecast'),rows.reduce((s,h)=>s+h.values[i],0)))}</td></tr></Table></Panel>;
}
export function IncomeTable(){const {year,plan,state,setTracking}=usePlan();return <Panel title="Revenue and technology-transfer earnings" aside={<span>INR crore · separate from collections</span>}><Table headers={['Income','Annual plan','YTD recognised','FY forecast','Variance to plan']}>{[{id:'coreIncome',name:'Customer revenue',budget:plan.revenue},{id:'totIncome',name:'Technology-transfer earnings',budget:plan.tot}].map(r=><tr key={r.id}><th>{r.name}</th><td>{inr(r.budget)}</td><td><NumberInput label={`${r.name} actual`} value={tracked(state.tracking,year,r.id,'actual')} onChange={v=>setTracking(r.id,'actual',v)}/></td><td><NumberInput label={`${r.name} forecast`} value={tracked(state.tracking,year,r.id,'forecast')} onChange={v=>setTracking(r.id,'forecast',v)}/></td><td>{variance(delta(tracked(state.tracking,year,r.id,'forecast'),r.budget))}</td></tr>)}</Table></Panel>;}
