import { useState } from 'react';
import { AS_OF, OPPORTUNITIES, STAGES, date, days, nearClosure, usd, type Segment } from '@/data/md-scenario';
import { Badge, Cards, Choice, Empty, Metric, Panel, Table, type Inspect } from './Shared';
export default function BusinessDevelopment({ inspect, initial = 'All' }: { inspect: Inspect; initial?: string }) {
 const [segment,setSegment]=useState('All'); const [filter,setFilter]=useState(initial); const [stage,setStage]=useState<number|null>(null);
 const scope=OPPORTUNITIES.filter(o=>segment==='All'||o.segment===segment);
 const rows=scope.filter(o=>(filter!=='Customer-backed'||o.backed)&&(filter!=='Near closure'||nearClosure(o))&&(stage===null||o.stage===stage));
 const total=scope.reduce((s,o)=>s+o.value,0); const backed=scope.filter(o=>o.backed).length;
 return <><Cards><Metric label="Customer-backed programmes" value={`${backed} / 2`} onClick={()=>setFilter('Customer-backed')}/><Metric label="Active opportunities" value={scope.length} onClick={()=>{setFilter('All');setStage(null);}}/><Metric label="Pipeline value" value={usd(total)}/><Metric label="Near closure · 90 days" value={usd(scope.filter(nearClosure).reduce((s,o)=>s+o.value,0))} sub={`${scope.filter(nearClosure).length} deals`} onClick={()=>setFilter('Near closure')}/></Cards>
 <div className="mc-controls"><Choice label="BD segment" value={segment} options={['All','B2B','B2G','PSUs']} onChange={v=>{setSegment(v);setStage(null);}}/><Choice label="Opportunity filter" value={filter} options={['All','Customer-backed','Near closure']} onChange={setFilter}/></div>
 <Panel title="Pipeline"><div className="mc-pipeline">{segment==='All'?(['B2B','B2G','PSUs'] as Segment[]).map(s=>{const a=OPPORTUNITIES.filter(o=>o.segment===s);return <button key={s} onClick={()=>setSegment(s)}><span>{s}</span><strong>{usd(a.reduce((n,o)=>n+o.value,0))}</strong><small>{a.length} opportunities</small><i style={{width:`${a.reduce((n,o)=>n+o.value,0)/total*100}%`}}/></button>}):STAGES[segment as Segment].map((s,i)=>{const a=scope.filter(o=>o.stage===i);return <button key={s} aria-pressed={stage===i} onClick={()=>setStage(stage===i?null:i)}><span>{s}</span><strong>{a.length}</strong><small>{usd(a.reduce((n,o)=>n+o.value,0))}</small><i style={{width:`${a.length/scope.length*100}%`}}/></button>})}</div></Panel>
 <Panel title="Active pursuits" aside={<span>{rows.length} projects {stage!==null&&<button className="mc-link" onClick={()=>setStage(null)}>Clear stage</button>}</span>}><Table headers={['Customer / project','Route / stage','Value','Next decision','Due / owner','Risk']}>{rows.map(o=><tr key={o.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:o.project,rows:[['Customer',o.customer],['Route',o.route],['Stage',STAGES[o.segment][o.stage]],['Scope value',usd(o.value)],['Customer commitment',o.commitment],['Target signature',date(o.close)],['Next decision',`${o.decision} · ${date(o.due)}`],['Owner',o.owner],['Risk',o.risk]]})}>{o.customer}</button><small>{o.project}</small></th><td><Badge>{o.segment}</Badge><small>{STAGES[o.segment][o.stage]}</small></td><td>{usd(o.value)}</td><td>{o.decision}</td><td>{date(o.due)}<small>{o.owner}</small></td><td><Badge tone="amber">{o.risk}</Badge></td></tr>)}</Table>{!rows.length&&<Empty text="0 opportunities in this selection"/>}</Panel>
 <Panel title="Next commercial commitments"><div className="mc-commitments">{scope.filter(o=>days(AS_OF,o.due)<=30).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,3).map(o=><button key={o.id} onClick={()=>inspect({title:o.decision,rows:[['Project',o.project],['Date',date(o.due)],['Owner',o.owner],['Commitment',o.commitment]]})}><span>{date(o.due)}</span><strong>{o.decision}</strong><small>{o.customer}</small></button>)}</div></Panel></>;
}
