import { useState } from 'react';
import { ARMY, BLOCKERS, DELIVERY, date, days, usd } from '@/data/md-scenario';
import { Badge, Cards, Choice, Empty, Gantt, Metric, Panel, Table, type Inspect } from './Shared';
export default function Delivery({ inspect, initial='All' }: { inspect: Inspect; initial?: string }) {
 const [filter,setFilter]=useState(initial); const next=DELIVERY[0];
 const rows=DELIVERY.filter(m=>filter!=='At risk'||days(m.due,m.forecast)>0);
 return <><Cards><Metric label="Next milestone variance" value={`+${days(next.due,next.forecast)} days`} sub={`+${days(next.previous,next.forecast)} days since last review`} tone="mc-amber" onClick={()=>setFilter('At risk')}/><Metric label="Milestone blockers" value={BLOCKERS.filter(b=>b.project==='army').length} sub="Customer inputs · HQ access" onClick={()=>inspect({title:'Army blockers',rows:BLOCKERS.filter(b=>b.project==='army').map(b=>[b.label,`${b.owner} · ${date(b.due)} · ${b.impact}`])})}/><Metric label="Confirmed order" value={usd(ARMY.value)} sub="3 years · Oct 2026–Sep 2029"/><Metric label="Next acceptance receipt" value={usd(100)} sub="April 2027 acceptance gate" onClick={()=>inspect({title:'First acceptance receipt',rows:[['Order',ARMY.name],['Acceptance',date('2027-04-01')],['Payment due',date('2027-05-01')],['Amount',usd(100)],['Condition','Customer acceptance and invoice']]})}/></Cards>
 <div className="mc-controls"><label>Programme <select aria-label="Delivery programme"><option>{ARMY.name}</option></select></label><Choice label="Delivery milestone filter" value={filter} options={['All','At risk']} onChange={setFilter}/></div>
 <Panel title="Delivery schedule" aside={<Badge>1 confirmed order</Badge>}><Gantt items={rows} inspect={inspect}/></Panel>
 <Panel title="Milestone commitments"><Table headers={['Milestone','Agreed date','Forecast','Movement','Owner']}>{rows.map(m=><tr key={m.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:m.label,rows:[['Order',ARMY.name],['Dependency',m.dependency],['Owner',m.owner],['Baseline',date(m.due)],['Forecast',date(m.forecast)]]})}>{m.label}</button></th><td>{date(m.due)}</td><td>{date(m.forecast)}</td><td><Badge tone={days(m.due,m.forecast)>0?'amber':''}>{days(m.previous,m.forecast)>0?'+':''}{days(m.previous,m.forecast)}d / week</Badge></td><td>{m.owner}</td></tr>)}</Table>{!rows.length&&<Empty text="0 milestones in this selection"/>}</Panel></>;
}
