import { useState } from 'react';
import { ARMY, AS_OF, BLOCKERS, DELIVERY, DELIVERY_ACCEPTANCE, date, days, usd } from '@/data/md-scenario';
import { Badge, Cards, Choice, Empty, Gantt, Metric, Panel, Table, type Inspect } from './Shared';
export default function Delivery({ inspect, initial='All' }: { inspect: Inspect; initial?: string }) {
 const [filter,setFilter]=useState(initial); const next=DELIVERY[0];
 const rows=DELIVERY.filter(m=>(filter!=='At risk'||days(m.due,m.forecast)>0)&&(filter!=='Due · 90d'||days(AS_OF,m.due)>=0&&days(AS_OF,m.due)<=90));
 return <><Cards><Metric label="Next milestone variance" value={`+${days(next.due,next.forecast)} days`} sub={`+${days(next.previous,next.forecast)} days WoW`} tone="mc-amber" onClick={()=>setFilter('At risk')}/><Metric label="Milestones accepted on time" value={DELIVERY_ACCEPTANCE.percentage === null ? `${DELIVERY_ACCEPTANCE.onTime} / ${DELIVERY_ACCEPTANCE.due}` : `${DELIVERY_ACCEPTANCE.percentage}%`} sub={DELIVERY_ACCEPTANCE.percentage === null ? 'accepted on time / due' : `${DELIVERY_ACCEPTANCE.onTime} / ${DELIVERY_ACCEPTANCE.due} due · programme to date`} onClick={()=>inspect({title:'Milestones accepted on time',rows:[['Period',`${date(ARMY.start)} – ${date(AS_OF)}`],['Accepted on time',String(DELIVERY_ACCEPTANCE.onTime)],['Milestones due',String(DELIVERY_ACCEPTANCE.due)],...DELIVERY.filter(m=>m.due>=ARMY.start&&m.due<=AS_OF).map(m=>[m.label,`Due ${date(m.due)} · ${m.acceptedAt ? `Accepted ${date(m.acceptedAt)}` : 'Awaiting acceptance'}`] as [string,string])]})}/><Metric label="Milestones completed / due · 90d" value={`${DELIVERY.filter(m=>days(AS_OF,m.due)>=0&&days(AS_OF,m.due)<=90&&m.progress===100).length} / ${DELIVERY.filter(m=>days(AS_OF,m.due)>=0&&days(AS_OF,m.due)<=90).length}`} onClick={()=>setFilter('Due · 90d')}/><Metric label="Next acceptance receipt" value={usd(100)} sub="01 May 2027" onClick={()=>inspect({title:'First acceptance receipt',rows:[['Order',ARMY.name],['Acceptance',date('2027-04-01')],['Payment due',date('2027-05-01')],['Amount',usd(100)],['Condition','Customer acceptance and invoice']]})}/></Cards>
 <div className="mc-controls"><label>Programme <select aria-label="Delivery programme"><option>{ARMY.name}</option></select></label><Choice label="Delivery milestone filter" value={filter} options={['All','At risk','Due · 90d']} onChange={setFilter}/></div>
 <Panel title="Delivery schedule" aside={<Badge>1 confirmed order</Badge>}><Gantt items={rows} inspect={inspect}/></Panel>
 <Panel title="Milestone commitments"><Table headers={['Milestone','Agreed date','Forecast','Movement','Owner']}>{rows.map(m=><tr key={m.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:m.label,rows:[['Order',ARMY.name],['Dependency',m.dependency],['Owner',m.owner],['Baseline',date(m.due)],['Forecast',date(m.forecast)]]})}>{m.label}</button></th><td>{date(m.due)}</td><td>{date(m.forecast)}</td><td><Badge tone={days(m.due,m.forecast)>0?'amber':''}>{days(m.previous,m.forecast)>0?'+':''}{days(m.previous,m.forecast)}d / week</Badge></td><td>{m.owner}</td></tr>)}</Table>{!rows.length&&<Empty text="0 milestones in this selection"/>}</Panel>
 <Panel title="Milestone blockers"><Table headers={['Blocker','Owner','Resolve by','Impact']}>{BLOCKERS.filter(b=>b.project==='army').map(b=><tr key={b.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:b.label,rows:[['Owner',b.owner],['Opened',date(b.opened)],['Resolve by',date(b.due)],['Impact',b.impact],['Action',b.action]]})}>{b.label}</button></th><td>{b.owner}</td><td>{date(b.due)}</td><td>{b.impact}</td></tr>)}</Table></Panel></>;
}
