import { useState } from 'react';
import { CAPACITY, ENGINEERING_READINESS, SCENARIOS, AS_OF, ENGINEERING_PERIOD_START, engineeringMetrics, date } from '@/data/md-scenario';
import { Badge, Bars, Cards, Choice, Empty, Metric, Panel, Table, type Inspect } from './Shared';
export default function Engineering({ inspect, initial='All' }: { inspect: Inspect; initial?: string }) {
 const [project,setProject]=useState('army');const [filter,setFilter]=useState(initial);
 const metrics=engineeringMetrics(project);
 const scope=SCENARIOS.filter(s=>s.project===project);const rows=scope.filter(s=>filter==='All'||s.state===filter);
 return <><Cards><Metric label="Engineering commitments delivered" value={metrics.percentage===null?`${metrics.delivered} / ${metrics.due.length}`:`${metrics.percentage}%`} sub={`${metrics.delivered} / ${metrics.due.length} due`} onClick={()=>inspect({title:'Engineering commitments delivered',rows:[['Period',`${date(ENGINEERING_PERIOD_START)} – ${date(AS_OF)}`],...metrics.due.map(c=>[c.label,`Due ${date(c.due)} · ${c.acceptedAt?`Accepted ${date(c.acceptedAt)}`:'Awaiting acceptance'}`] as [string,string])]})}/><Metric label="Critical engineering blockers" value={metrics.blockers.length} sub={metrics.blockers.length?`Oldest ${metrics.oldest} days`:undefined} onClick={()=>inspect({title:'Critical engineering blockers',rows:metrics.blockers.map(b=>[b.label,`${b.owner} · Opened ${date(b.opened)} · Resolve by ${date(b.due)}`])})}/><Metric label="Unresolved test failures" value={scope.filter(s=>s.state==='Failed').length} onClick={()=>setFilter('Failed')} tone="mc-amber"/><Metric label="Engineering capacity" value={`${CAPACITY[0].assigned} / ${CAPACITY[0].current}`} sub="Army 10 · Presales 2"/></Cards>
 <div className="mc-controls"><label>Platform / project <select aria-label="Engineering project" value={project} onChange={e=>{setProject(e.target.value);setFilter('All');}}><option value="army">V-BAT · Army ISR</option><option value="oem-isr">OEM A · Presales evaluation</option></select></label><Choice label="Scenario status" value={filter} options={['All','Passed','Failed','Ready','Blocked']} onChange={setFilter}/></div>
 <Panel title="Engineering commitments"><Table headers={['Output','Due','Accepted','Owner']}>{metrics.commitments.map(c=><tr key={c.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:c.label,rows:[['Acceptance check',c.check],['Due',date(c.due)],['Accepted',c.acceptedAt?date(c.acceptedAt):'Awaiting acceptance'],['Owner',c.owner]]})}>{c.label}</button></th><td>{date(c.due)}</td><td>{c.acceptedAt?date(c.acceptedAt):<Badge tone={c.due<=AS_OF?'amber':''}>{c.due<=AS_OF?'Overdue':'Pending'}</Badge>}</td><td>{c.owner}</td></tr>)}</Table></Panel>
 <div className="mc-two"><Panel title="Scenario validation"><Bars data={['Passed','Failed','Ready','Blocked'].map(state=>({label:state,count:scope.filter(s=>s.state===state).length}))} series={[{key:'count',name:'Scenarios',color:'#80b4fa'}]}/></Panel><Panel title={project==='army'?'Platform readiness · V-BAT':'Platform readiness · OEM A'}><div className="mc-progress-list">{(project==='army'?ENGINEERING_READINESS:[{label:'Platform information',complete:1,total:2},{label:'Integration scope',complete:1,total:2},{label:'Partner inputs',complete:0,total:2}]).map(r=><div key={r.label}><span>{r.label}<b>{r.complete} / {r.total}</b></span><progress max={r.total} value={r.complete}/></div>)}</div><div className="mc-footer-stat"><span>Next demonstration</span><strong>{project==='army'?'05 Feb 2027':'16 Oct 2026 · scope review'}</strong></div></Panel></div>
 <Panel title="Engineering workstreams"><Table headers={['Scenario / platform','Status','Next output','Due','Owner']}>{rows.map(s=><tr key={s.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:s.label,rows:[['Platform',s.platform],['Project',s.project==='army'?'Army order':'OEM A · approved presales'],['Status',s.state],['Next output',s.next],['Due',date(s.due)],['Owner',s.owner]]})}>{s.label}</button><small>{s.platform}</small></th><td><Badge tone={s.state==='Passed'?'green':s.state==='Failed'||s.state==='Blocked'?'amber':''}>{s.state}</Badge></td><td>{s.next}</td><td>{date(s.due)}</td><td>{s.owner}</td></tr>)}</Table>{!rows.length&&<Empty text="0 scenarios in this status"/>}</Panel></>;
}
