import { useState } from 'react';
import { ARMY, AS_OF, CASH_CURVE, CASH_FORECAST, CONFIRMED_FUNDING, COSTS, CURRENT_BURN, CURRENT_CASH, FUNDING_COVERAGE, PAYMENTS, RECOGNISED_REVENUE, REVENUE_PLAN, date, days, inr, usd } from '@/data/md-scenario';
import { Badge, Bars, Cards, Choice, Empty, Lines, Metric, Panel, Table, type Inspect } from './Shared';
export default function Finance({ inspect }: { inspect: Inspect }) {
 const [window,setWindow]=useState('Full contract');
 const actual=COSTS.reduce((s,c)=>s+c.actual,0); const budget=COSTS.reduce((s,c)=>s+c.budget,0);
 const payments=PAYMENTS.filter(p=>window==='Full contract'||!p.received&&days(AS_OF,p.due)>=0&&days(AS_OF,p.due)<=90);
 return <><Cards><Metric label="Available India cash" value={inr(CURRENT_CASH)} onClick={()=>inspect({title:'India funding',rows:[['Accessible cash',inr(CURRENT_CASH)],['Confirmed HQ funding',inr(CONFIRMED_FUNDING)],['Transfer date','01 Dec 2026'],['Contract receipts','Held separately by contracting entity']]})}/><Metric label="Funding coverage" value={`${FUNDING_COVERAGE} months`} tone="mc-green"/><Metric label="Current monthly burn" value={inr(CURRENT_BURN)}/><Metric label="Budget variance · Sep" value={`+${((actual-budget)/budget*100).toFixed(1)}%`} sub={`${inr(actual)} actual / ${inr(budget)} budget`} tone="mc-amber"/></Cards>
 <div className="mc-two"><Panel title="India cash forecast" aside={<span>INR crore · 18 months</span>}><Lines data={CASH_CURVE.map(m=>({label:m.month,balance:m.balance,burn:m.burn}))} unit="Cr" series={[{key:'balance',name:'Closing cash',color:'#80b4fa'},{key:'burn',name:'Monthly burn',color:'#d5b17a'}]}/></Panel><Panel title="Last closed month · September" aside={<span>INR crore</span>}><Bars data={COSTS.map(c=>({label:c.label.split(' / ')[0],budget:c.budget,actual:c.actual}))} unit="Cr" series={[{key:'budget',name:'Budget',color:'#53677f'},{key:'actual',name:'Actual',color:'#80b4fa'}]}/></Panel></div>
 <div className="mc-strip"><span>Oct–Dec expenditure <b>{inr(CASH_FORECAST.slice(0,3).reduce((s,m)=>s+m.burn,0))}</b></span><span>Jan–Mar expenditure <b>{inr(CASH_FORECAST.slice(3,6).reduce((s,m)=>s+m.burn,0))}</b></span><span>HQ funding · 01 Dec <b>{inr(CONFIRMED_FUNDING)}</b></span></div>
 <Panel title="Army contract · USD" aside={<span>01 Oct 2026–30 Sep 2029</span>}><div className="mc-finance-ledger">{[['Signed order',usd(ARMY.value)],['Recognised revenue',usd(RECOGNISED_REVENUE)],['Invoiced',usd(50)],['Cash collected',usd(PAYMENTS.filter(p=>p.received).reduce((s,p)=>s+p.amount,0))],['Outstanding invoices',usd(0)],['Unbilled order value',usd(PAYMENTS.filter(p=>!p.received).reduce((s,p)=>s+p.amount,0))]].map(([l,v])=><button key={l} onClick={()=>inspect({title:l,rows:[['Amount',v],['Entity',ARMY.entity],['Basis',l==='Recognised revenue'?'No performance obligations assumed satisfied at this snapshot. Advance is not earned revenue.':'See constructed Army contract and payment assumptions.']]})}><span>{l}</span><strong>{v}</strong></button>)}</div></Panel>
 <Panel title="Contract revenue & receipts forecast" aside={<span>USD millions · calendar year</span>}><Bars data={[2026,2027,2028,2029].map(year=>({label:String(year),revenue:REVENUE_PLAN.filter(r=>r.date.startsWith(String(year))).reduce((s,r)=>s+r.amount,0),receipts:PAYMENTS.filter(p=>p.due.startsWith(String(year))).reduce((s,p)=>s+p.amount,0)}))} unit="M" series={[{key:'revenue',name:'Recognised revenue plan',color:'#80b4fa'},{key:'receipts',name:'Contract receipts',color:'#53677f'}]}/></Panel>
 <Panel title="Billing & collection schedule" aside={<Choice label="Payment window" value={window} options={['Full contract','Next 90 days']} onChange={setWindow}/>}><Table headers={['Invoice / gate','Amount','Invoice date','Receipt date','Status']}>{payments.map(p=><tr key={p.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:p.label,rows:[['Invoice',p.id],['Order',ARMY.name],['Amount',usd(p.amount)],['Invoice date',date(p.invoice)],['Payment due',date(p.due)],['Condition',p.received?'Contract advance received':'Acceptance evidence and invoice'],['Licence / commercial','Scope and entitlements require confirmation before handover; no extra licence value assumed.']]})}>{p.label}</button><small>{p.id}</small></th><td>{usd(p.amount)}</td><td>{date(p.invoice)}</td><td>{date(p.due)}</td><td><Badge tone={p.received?'green':''}>{p.received?'Received':'Scheduled'}</Badge></td></tr>)}</Table>{!payments.length&&<Empty text="0 contractual receipts scheduled in the next 90 days"/>}</Panel></>;
}
