import { useState } from 'react';
import { CRITICAL_JOINING_GAPS, JOINING_COMMITMENTS, CURRENT_HEADCOUNT, HIRING_PLAN, ROLES, TARGET_HEADCOUNT, date } from '@/data/md-scenario';
import { Badge, Bars, Cards, Choice, Metric, Panel, Table, type Inspect } from './Shared';
export default function Hiring({ inspect, initial = 'All' }: { inspect: Inspect; initial?: string }) {
 const [filter,setFilter]=useState(initial);const rows=ROLES.filter(r=>filter!=='Critical'||r.critical);
 const sum=(key:'applied'|'screening'|'interviewing'|'offered'|'accepted'|'joined')=>ROLES.reduce((s,r)=>s+r[key],0);
 return <><Cards><Metric label="India headcount" value={`${CURRENT_HEADCOUNT} / ${TARGET_HEADCOUNT}`}/><Metric label="Six-month hires joined" value={`${sum('joined')} / 30`} sub={`${sum('joined')} / 5 · October joins`} onClick={()=>setFilter('All')}/><Metric label="Critical new roles filled" value={`${ROLES.filter(r=>r.critical).reduce((s,r)=>s+r.joined,0)} / ${ROLES.filter(r=>r.critical).reduce((s,r)=>s+r.count,0)}`} onClick={()=>setFilter('Critical')}/><Metric label="Accepted · awaiting joining" value={sum('accepted')} sub={`${sum('offered')} offers pending`} onClick={()=>inspect({title:'Joining commitments',rows:ROLES.filter(r=>r.accepted>0).map(r=>[r.role,`${r.accepted} accepted · required ${date(r.due)}`])})}/></Cards>
 <div className="mc-two"><Panel title="Headcount plan" aside={<span>Oct 2026–Mar 2027</span>}><Bars data={HIRING_PLAN.map((m,i)=>({label:m.month,planned:m.cumulative,...(i===0?{actual:CURRENT_HEADCOUNT}:{})}))} series={[{key:'planned',name:'Month-end plan',color:'#53677f'},{key:'actual',name:'Actual at 01 Oct',color:'#80b4fa'}]}/></Panel><Panel title="Candidate pipeline" aside={<span>{sum('applied')} applications to date</span>}><div className="mc-funnel">{(['screening','interviewing','offered','accepted','joined'] as const).map((k,i)=><div key={k}><span>{['Screening','Interviewing','Offer pending','Accepted','Joined'][i]}</span><div><i style={{width:`${Math.max(1,sum(k)/sum('screening')*100)}%`}}/></div><strong>{sum(k)}</strong></div>)}</div></Panel></div>
 <Panel title="Joining commitments" aside={<Choice label="Joining filter" value={filter==='Joining gaps'?'Joining gaps':'All'} options={['All','Joining gaps']} onChange={setFilter}/>}><Table headers={['Position','Required','Forecast','Status']}>{(filter==='Joining gaps'?CRITICAL_JOINING_GAPS:JOINING_COMMITMENTS).map(r=><tr key={r.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:r.id,rows:[['Position',r.role],['Milestone',r.milestone],['Required',date(r.due)],['Forecast',date(r.forecast)],['Joining date',r.confirmed?'Confirmed':'Unconfirmed']]})}>{r.id} · {r.role}</button></th><td>{date(r.due)}</td><td>{date(r.forecast)}</td><td><Badge tone={r.confirmed?'green':'amber'}>{r.confirmed?'Confirmed':'Gap'}</Badge></td></tr>)}</Table></Panel>
 <Panel title="Position plan" aside={<Choice label="Hiring priority" value={filter==='Critical'?'Critical':'All'} options={['All','Critical']} onChange={setFilter}/>}><Table headers={['Position','Openings','Stage','Interviews','Offers / accepted','Required start']}>{rows.map(r=><tr key={r.role}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:r.role,rows:[['Team',r.team],['Openings',String(r.count)],['Priority',r.critical?'Critical':'Planned'],['Applications',String(r.applied)],['Screening',String(r.screening)],['Interviewing',String(r.interviewing)],['Offers pending',String(r.offered)],['Accepted',String(r.accepted)],['Joined',String(r.joined)],['Required start',date(r.due)]]})}>{r.role}</button>{r.critical&&<small className="mc-amber">Critical</small>}</th><td>{r.count}</td><td><Badge>{r.stage}</Badge></td><td>{r.interviewing}</td><td>{r.offered} / {r.accepted}</td><td>{date(r.due)}</td></tr>)}</Table></Panel></>;
}
