import { useState } from 'react';
import { BLOCKERS, JSW, TRANSFERS, date, days } from '@/data/md-scenario';
import { Badge, Cards, Choice, Gantt, Metric, Panel, Table, type Inspect } from './Shared';
export default function JswPartnership({ inspect }: { inspect: Inspect }) {
 const [filter,setFilter]=useState('All');const [acceptance,setAcceptance]=useState('Pending');
 const rows=JSW.filter(m=>filter!=='At risk'||days(m.due,m.forecast)>0);
 return <><Cards><Metric label="Transfer deliverables accepted" value={`${TRANSFERS.filter(t=>t.accepted).length} / ${TRANSFERS.length}`} sub="Target 8 / 8 by 29 Oct" onClick={()=>setAcceptance('All')}/><Metric label="Initial production readiness" value="31 Dec" sub="2026 · forecast on plan"/><Metric label="Workstreams at risk" value={JSW.filter(m=>days(m.due,m.forecast)>0).length} sub="Tooling forecast +10 days" onClick={()=>setFilter('At risk')} tone="mc-amber"/><Metric label="Critical joint dependencies" value={BLOCKERS.filter(b=>b.project==='jsw').length} sub="Supplier approval due 09 Oct" onClick={()=>inspect({title:'Tooling supplier approval',rows:[['Owner','JSW procurement lead'],['Due','09 Oct 2026'],['Impact','Tooling readiness +10 days'],['Decision','Confirm supplier choice and release approval.']]})}/></Cards>
 <Panel title="Joint industrialisation schedule" aside={<Choice label="JSW workstream filter" value={filter} options={['All','At risk']} onChange={setFilter}/>}><Gantt items={rows} inspect={inspect}/></Panel>
 <Panel title="Transfer acceptance" aside={<Choice label="Transfer status" value={acceptance} options={['Pending','All']} onChange={setAcceptance}/>}><Table headers={['Deliverable','Shield owner','JSW receiver','Due','Acceptance']}>{TRANSFERS.filter(t=>acceptance==='All'||!t.accepted).map(t=><tr key={t.id}><th scope="row"><button className="mc-link" onClick={()=>inspect({title:t.label,rows:[['Responsible',t.owner],['Receiving owner',t.receiver],['Due',date(t.due)],['Accepted',t.accepted?'30 Sep 2026':'Pending'],['Gate','Receiving-owner sign-off against the agreed package. Training requires capability demonstration.']]})}>{t.label}</button></th><td>{t.owner}</td><td>{t.receiver}</td><td>{date(t.due)}</td><td><Badge tone={t.accepted?'green':''}>{t.accepted?'Accepted':'Pending'}</Badge></td></tr>)}</Table></Panel></>;
}
