import { YEARS, positionVariance, revenueAtRisk, type FinancialMilestone, type Position } from '@/data/md-plan';
import { inr } from '@/data/md-scenario';
import { usePlan } from './PlanContext';
import { NumberInput, money, variance } from './Budget';
import { Panel, Table, Empty } from './Shared';
export function PositionRegister(){
 const {year,state,update}=usePlan();const rows=state.positions.filter(r=>r.year===year);const patch=(id:string,p:Partial<Position>)=>update(s=>({...s,positions:s.positions.map(r=>r.id===id?{...r,...p}:r)}));
 return <Panel title="Position cost register" aside={<span>{year} · annual fully loaded cost, INR lakh</span>}><p className="mc-plan-note">Compare each hire with its role budget. ₹70 lakh is the blended team assumption, not a per-role ceiling. Joining delays can reduce spend while leaving delivery roles unfilled. Position costs inform HR’s full-year forecast below; a partial register never replaces the team forecast automatically.</p><Table headers={['Position / owner','Role budget','Offered / actual cost','Annual variance','Planned join','Expected join']}>{rows.map(r=><tr key={r.id}><th>{r.role}<small>{r.owner}</small></th><td><NumberInput label={`${r.role} budget lakh`} value={r.budget} onChange={v=>patch(r.id,{budget:v})}/></td><td><NumberInput label={`${r.role} cost lakh`} value={r.cost} onChange={v=>patch(r.id,{cost:v})}/></td><td className={(positionVariance(r)??0)>0?'mc-amber':''}>{positionVariance(r)===null?'Not loaded':`${positionVariance(r)!>0?'+':''}${positionVariance(r)!.toFixed(2)} L`}</td><td><input aria-label={`${r.role} planned join`} type="date" value={r.planned} onChange={e=>patch(r.id,{planned:e.target.value})}/></td><td><input aria-label={`${r.role} expected join`} type="date" value={r.start} onChange={e=>patch(r.id,{start:e.target.value})}/>{r.start>r.planned&&<small className="mc-amber">Joining later than plan</small>}</td></tr>)}</Table>{!rows.length&&<Empty text="No position costs loaded. Add approved roles to compare budgets with offers."/>}<details open className="mc-plan-fold"><summary>Add position</summary><form className="mc-entry-form" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);update(s=>({...s,positions:[...s.positions,{id:crypto.randomUUID(),year,role:String(d.get('role')),owner:String(d.get('owner')),budget:null,cost:null,planned:String(d.get('planned')),start:''}]}));ev.currentTarget.reset();}}><label>Role<input name="role" required/></label><label>Owner<input name="owner" required/></label><label>Planned joining<input name="planned" required type="date"/></label><button>Add position</button></form></details></Panel>;
}
export function MilestoneRegister({area}:{area:FinancialMilestone['area']}){
 const {year,state,update}=usePlan();const rows=state.milestones.filter(r=>r.year===year&&r.area===area);const patch=(id:string,p:Partial<FinancialMilestone>)=>update(s=>({...s,milestones:s.milestones.map(r=>r.id===id?{...r,...p}:r)}));
 return <Panel title={area==='Operations'?'Revenue milestone register':'Technology-transfer earnings milestones'} aside={<span>At risk: {money(revenueAtRisk(state.milestones,year,area))}</span>}><p className="mc-plan-note">Recognition / earnings milestones, not collection dates. Use one primary record per shared milestone ID so multiple blockers do not multiply revenue at risk. Annual forecasts are entered separately because a partial milestone register is not a complete forecast.</p><Table headers={['Milestone / owner','Value · crore','Agreed date','Forecast date','Status','Shared milestone ID / primary']}>{rows.map(r=><tr key={r.id}><th>{r.label}<small>{r.owner}</small></th><td><NumberInput label={`${r.label} value`} value={r.value} onChange={v=>patch(r.id,{value:v})}/></td><td>{r.due}</td><td><input aria-label={`${r.label} forecast date`} type="date" value={r.forecast} onChange={e=>patch(r.id,{forecast:e.target.value})}/></td><td><select aria-label={`${r.label} status`} value={r.status} onChange={e=>patch(r.id,{status:e.target.value as FinancialMilestone['status']})}>{['Pending','At risk','Accepted'].map(v=><option key={v}>{v}</option>)}</select></td><td><input aria-label={`${r.label} shared milestone ID`} value={r.group} onChange={e=>patch(r.id,{group:e.target.value})}/><label><input aria-label={`${r.label} primary value`} type="checkbox" checked={r.primary} onChange={e=>patch(r.id,{primary:e.target.checked})}/>Count value</label></td></tr>)}</Table>{!rows.length&&<Empty text="Annual targets are loaded; commercial milestone amounts and dates are not yet mapped."/>}<details open className="mc-plan-fold"><summary>Add commercial milestone</summary><form className="mc-entry-form" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);update(s=>({...s,milestones:[...s.milestones,{id:crypto.randomUUID(),year,area,label:String(d.get('label')),owner:String(d.get('owner')),due:String(d.get('due')),forecast:String(d.get('due')),value:null,status:'Pending',group:'',primary:true}]}));ev.currentTarget.reset();}}><label>Milestone<input required name="label"/></label><label>Owner<input required name="owner"/></label><label>Agreed date<input required name="due" type="date"/></label><button>Add milestone to {year}</button></form></details></Panel>;
}
