import { Fragment, useState, type ReactNode } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, LineChart, Line, Legend } from 'recharts';
import { AS_OF, date, days, type Milestone } from '@/data/md-scenario';
export interface Detail { title: string; rows: [string, string][] }
export type Inspect = (detail: Detail) => void;
export function Cards({ children }: { children: ReactNode }) { return <div className="mc-cards">{children}</div>; }
export function Metric({ label, value, sub, onClick, tone = '' }: { label: string; value: ReactNode; sub?: string; onClick?: () => void; tone?: string }) {
 const content = <><span className="mc-metric-label">{label}{onClick && <ArrowUpRight size={14}/>}</span><strong className={tone}>{value}</strong>{sub && <small>{sub}</small>}</>;
 return onClick ? <button className="mc-card" onClick={onClick}>{content}</button> : <div className="mc-card">{content}</div>;
}
export function Panel({ title, aside, children }: { title: string; aside?: ReactNode; children: ReactNode }) { return <section className="mc-panel"><div className="mc-panel-title"><h2>{title}</h2>{aside}</div>{children}</section>; }
export function Badge({ children, tone = '' }: { children: ReactNode; tone?: string }) { return <span className={`mc-badge ${tone}`}>{children}</span>; }
export function Choice({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <div className="mc-choices" role="group" aria-label={label}>{options.map(o=><button key={o} aria-pressed={value===o} onClick={()=>onChange(o)}>{o}</button>)}</div>; }
export function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="mc-table-scroll"><table><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
export function Empty({ text }: { text: string }) { return <div className="mc-empty">{text}</div>; }
const axis = { fill: '#969a9f', fontSize: 11 };
const tip = { backgroundColor: '#191d22', border: '1px solid #414952', color: '#eceef2', borderRadius: 6 };
export function Bars({ data, series, unit = '', stacked = false }: { data: Record<string, string | number>[]; series: { key: string; name: string; color: string }[]; unit?: string; stacked?: boolean }) { return <div className="mc-chart" role="img" aria-label={`${series.map(s=>s.name).join(' and ')} chart, ${unit}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{right:12,left:0,top:12,bottom:0}}><CartesianGrid stroke="#2b3037" vertical={false}/><XAxis dataKey="label" tick={axis} axisLine={false} tickLine={false}/><YAxis tick={axis} axisLine={false} tickLine={false} width={42}/><Tooltip contentStyle={tip} labelStyle={{color:'#eceef2'}} formatter={(v)=>`${Number(v).toFixed(Number(v)%1 ? 2 : 0)}${unit}`}/><Legend iconType="circle" wrapperStyle={{fontSize:11}}/>{series.map(s=><Bar isAnimationActive={false} key={s.key} dataKey={s.key} name={s.name} fill={s.color} stackId={stacked?'a':undefined} radius={[3,3,0,0]}/>)}</BarChart></ResponsiveContainer></div>; }
export function Lines({ data, series, unit = '' }: { data: Record<string,string|number>[]; series: { key: string; name: string; color: string }[]; unit?: string }) { return <div className="mc-chart" role="img" aria-label={`${series.map(s=>s.name).join(' and ')} chart, ${unit}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{right:15,left:0,top:12,bottom:0}}><CartesianGrid stroke="#2b3037" vertical={false}/><XAxis dataKey="label" tick={axis} axisLine={false} tickLine={false}/><YAxis tick={axis} width={42} axisLine={false} tickLine={false}/><Tooltip contentStyle={tip} labelStyle={{color:'#eceef2'}} formatter={(v)=>`${Number(v).toFixed(2)}${unit}`}/><Legend iconType="circle" wrapperStyle={{fontSize:11}}/>{series.map(s=><Line isAnimationActive={false} key={s.key} dataKey={s.key} name={s.name} stroke={s.color} strokeWidth={2.5} dot={false}/>)}</LineChart></ResponsiveContainer></div>; }
export function Gantt({ items, inspect, initial = '6 months', horizons = ['6 months','18 months','36 months'] }: { items: Milestone[]; inspect: Inspect; initial?: string; horizons?: string[] }) {
 const [horizon,setHorizon]=useState(initial);
 const count = parseInt(horizon); const start='2026-10-01'; const end=new Date(Date.UTC(2026,9+count,1)).toISOString().slice(0,10); const total=days(start,end);
 const pos=(d:string)=>Math.min(100,Math.max(0,days(start,d)/total*100));
 const visible=items.filter(m=>days(m.start,end)>0 && days(start,m.forecast)>=0);
 return <><div className="mc-gantt-toolbar"><Choice label="Timeline horizon" value={horizon} options={horizons} onChange={setHorizon}/><span><i className="mc-key baseline"/> Baseline <i className="mc-key forecast"/> Forecast</span></div><div className="mc-gantt-scroll"><div className="mc-gantt" style={{minWidth:count>18?1050:850}}><div className="mc-gantt-head"><span>Milestone</span><div className="mc-gantt-months">{Array.from({length:count>18?12:count},(_,i)=>{const d=new Date(Date.UTC(2026,9+i*(count>18?3:1),1));return <span key={i} style={{ position: 'absolute', left: `${pos(d.toISOString().slice(0,10))}%` }}>{d.toLocaleDateString('en-GB',{month:'short',year:'2-digit',timeZone:'UTC'})}</span>;})}</div><span>Variance</span></div>{visible.map((m,index)=>{const variance=days(m.due,m.forecast);return <Fragment key={m.id}>{(index===0||visible[index-1].group!==m.group)&&<div className="mc-gantt-group">{m.group}</div>}<button className="mc-gantt-row" key={m.id} onClick={()=>inspect({title:m.label,rows:[['Workstream',m.group],['Owner',m.owner],['Baseline',`${date(m.start)} → ${date(m.due)}`],['Forecast',m.forecastPending?'Not baselined':date(m.forecast)],['Weekly movement',m.forecastPending?'Not baselined':`${days(m.previous,m.forecast)>0?'+':''}${days(m.previous,m.forecast)} days`],['Work complete',m.progressLabel ?? `${m.progress}%`],['Dependency',m.dependency]]})}><span>{m.label}<small>{m.owner}</small>{m.progressLabel && <small>{m.progressLabel} · {date(m.due)} → {m.forecastPending ? 'TBD' : date(m.forecast)}</small>}</span><div className="mc-gantt-track"><span className="mc-gantt-baseline" style={{left:`${pos(m.start)}%`,width:`${Math.max(.6,pos(m.due)-pos(m.start))}%`}}/>{!m.forecastPending && <span className={`mc-gantt-forecast ${variance>0?'late':''}`} style={{left:`${pos(m.start)}%`,width:`${Math.max(.6,pos(m.forecast)-pos(m.start))}%`}}><i style={{width:`${m.progress}%`}}/></span>}<span className="mc-today" style={{left:`${pos(AS_OF)}%`}}/></div><span className={variance>0?'mc-amber':'mc-muted'}>{m.forecastPending?'TBD':variance>0?`+${variance}d`:m.progressLabel?'0d':'On plan'}</span></button></Fragment>})}</div></div>{!visible.length && <Empty text="No milestones in this horizon. Select a longer horizon."/>}</>;
}
