import { Headline, Screen } from '@/components/ui';
import './cadence.css';

const meetings = [
  { name: 'OPERATE', timing: 'Weekly · 20 min', question: 'Recover commitments at risk', participants: 'Chief of Staff + accountable owners; MD only for escalations.', input: 'Changed forecasts, next 30–60 day gates and overdue actions from existing records.', agenda: '5 min changes · 10 min recovery choices · 5 min owners and dates.', authority: 'Functional owners act within delegated budget and scope. Cross-team priority conflicts go to the MD.', output: 'A recovery action, owner and date for each exception. No routine green updates.' },
  { name: 'ALIGN', timing: 'At a blocked milestone · 25 min', question: 'Resolve a specific dependency', participants: 'India owner + relevant HQ or JSW counterpart; decision authority attends.', input: 'One blocked gate, options, impact and latest safe decision date.', agenda: '5 min evidence · 15 min resolve trade-off · 5 min commitment.', authority: 'Named gate owner retains technical sign-off. MD resolves India priorities; HQ decides commitments outside India authority.', output: 'One agreed hand-off with acceptance evidence and date. Cancel when no dependency needs resolution.' },
  { name: 'STEER', timing: 'Monthly · 45 min', question: 'Make the resource and risk choices', participants: 'MD + Chief of Staff + Finance; other leads join their decision slot.', input: 'One-page dashboard 24h ahead: KPIs versus plan, forecast changes and at most 3 decision requests.', agenda: '5 min changes · 30 min decisions · 10 min commitments and closure.', authority: 'MD decides India resource allocation and escalation within delegated authority. Funding / scope beyond that authority goes to HQ.', output: 'Decision, rationale, accountable person, due date and closure test entered in the existing log the same day.' },
  { name: 'RESET', timing: 'Quarterly · 60 min', question: 'Rebalance the India portfolio', participants: 'MD + India leads + relevant HQ sponsor.', input: 'Portfolio evidence, delivery / cash outlook and results of prior resource choices.', agenda: '15 min outcomes · 30 min portfolio choices · 15 min resource envelope.', authority: 'MD recommends what to accelerate, pause or stop; HQ approves changes beyond the agreed India envelope.', output: 'Updated priorities and resource limits. Revise thresholds explicitly; retain the prior baseline.' },
];

export default function Cadence() {
  return <Screen className="cadence-screen cadence-operating">
    <Headline title="Run by exception. Decide at the right level." />
    <p className="cadence-intro">Proposed operating agreement · one dashboard, one decision log, existing source records. The Chief of Staff prepares decisions and tracks closure; functional owners run execution.</p>
    <section className="cadence-monthly panel" aria-labelledby="monthly-agenda"><div><span className="cadence-eyebrow">Monthly MD review</span><h2 id="monthly-agenda">45 minutes. Three decisions maximum.</h2><p>Pre-read 24 hours ahead. No presentation round-robin.</p></div><div className="cadence-agenda"><span><strong>05</strong>Changes</span><span><strong>30</strong>Decisions</span><span><strong>10</strong>Commitments</span></div></section>
    <section className="cadence-meetings" aria-label="Operating cadence">{meetings.map(m => <article className="panel cadence-meeting" key={m.name}><div className="cadence-meeting-heading"><span className="cadence-eyebrow">{m.name}</span><span>{m.timing}</span></div><h2>{m.question}</h2><p>{m.participants}</p><dl><div><dt>Input</dt><dd>{m.input}</dd></div><div><dt>Output</dt><dd>{m.output}</dd></div></dl><details><summary>Agenda & decision rights</summary><p>{m.agenda}</p><p>{m.authority}</p></details></article>)}</section>
    <section className="cadence-rules" aria-label="Escalation and reporting rules"><article className="panel"><h2>Escalate between meetings</h2><p>A required gate approval missing at release, or a commitment preceding confirmed funding: contact the MD and relevant authority immediately; hold the affected new release or commitment.</p><p>Forecast slippage over 7 days or a critical role still unassigned 14 days before its gate: owner brings impact, options and a recommendation within 24 hours.</p><p>These are proposed triggers, to be agreed with the MD. Missing evidence stays unverified. The dashboard carries the owner and next evidence date.</p></article><article className="panel"><h2>Keep bureaucracy out</h2><p>Exclude full CRM exports, meeting counts, routine green updates, detailed project plans and the four-year model from the monthly pre-read. Keep them available as drill-downs.</p><p>Owners update only changed forecasts, exceptions and decision requests in existing records. The Chief of Staff assembles the page; no parallel reporting spreadsheet.</p><p>Review overdue actions weekly. Close only with evidence; reopen if the forecast fails to improve. Keep completed decisions in history, off the main page.</p></article></section>
  </Screen>;
}
