import { MONTHLY_REVIEWS, WEEKLY_REVIEWS, REVIEW_HEADROOM } from '@/data/md-reviews';

const decisions = [
  { id: 'D01', title: 'Prioritise Army recovery', due: '07 Sep', owner: 'Programme lead', recommendation: 'Reserve India engineering for acceptance; request temporary HQ support before starting OEM integration.', tradeoff: 'OEM discovery can continue, but integration waits. Extra support has a cost; assume the support allocation recovers 7 days.', closure: 'By 09 Sep: named staffing plan and a customer-aligned recovery forecast. MD decides allocation; HQ approves its support.' },
  { id: 'D02', title: 'Approve Shield India operating spend', due: '07 Sep · before commitment', owner: 'Finance lead', recommendation: 'Approve the assumed $660k Shield India operating envelope for the next 13 weeks; prioritise acceptance support, staffing and essential overhead.', tradeoff: 'Additional engineering support uses the same operating envelope; defer discretionary travel and hiring if recovery costs rise. JSW manages its production procurement.', closure: 'By 08 Sep: Finance and HQ agree the India operating allocation, spending owners and recovery allowance. Escalate spending beyond the agreed envelope to HQ.' },
  { id: 'D03', title: 'Resolve JSW production dependencies', due: '09 Sep · partner review', owner: 'Industrialisation lead', recommendation: 'Agree with JSW the owners and dates for the 2 remaining readiness checks; prioritise Shield technology-transfer and engineering support needed for production.', tradeoff: 'More Shield engineering support for JSW may compete with Army acceptance recovery. JSW owns production execution under this planning assumption.', closure: 'By 11 Sep: joint readiness checklist, named JSW and Shield owners, and an agreed delivery forecast. The MD resolves Shield support priorities and escalates partner dependencies.' },
];
const triggers = [
  ['Delivery / capacity', 'Red · acceptance +14 days; 5 engineers uncovered', 'Forecast slips >7 days, or a critical role remains unassigned 14 days before its gate.', 'Programme lead → MD within 24h; recovery plan due 09 Sep.'],
  ['Cash', 'Assumed · $1.48M minimum headroom', 'Any week below the approved cash floor, or a commitment falls due before confirmed funding.', 'Finance lead → MD / HQ Treasury before commitment; evidence due 08 Sep.'],
  ['Readiness / approvals', 'Assumed · 8 / 10 readiness checks complete', 'Either of the 2 JSW readiness sign-offs slips beyond 11 Sep, or Shield support cannot meet the agreed production date.', 'Industrialisation lead → MD + JSW counterpart within 24h; agree recovery owners and dates by 11 Sep.'],
  ['Data / decisions', 'Assumed · 3 open actions; 1 overdue', 'An action misses its due date, or a critical source misses its agreed refresh.', 'Chief of Staff → accountable owner same day; flag to MD if unresolved in 24h.'],
];

export default function MdMonthlyReview() {
  const week = WEEKLY_REVIEWS[0], prior = WEEKLY_REVIEWS[1], month = MONTHLY_REVIEWS[0];
  const cost = month.rows.find(row => row.label === 'Local operating cost')!;
  const gap = week.engineersNeeded - week.engineersAvailable;
  const money = (n: number) => `$${Math.round(n * 1000).toLocaleString('en-US')}k`;
  const kpis = [
    { label: 'Acceptance forecast', value: week.forecastAcceptance, plan: `Committed ${week.plannedAcceptance}`, delta: `${week.lateDays} days late · +${week.lateDays - prior.lateDays} days vs prior week`, status: 'Red', tone: 'red' },
    { label: 'Engineering coverage', value: `${week.engineersAvailable} / ${week.engineersNeeded}`, plan: `${gap} engineers uncovered`, delta: `Gap was ${prior.engineersNeeded - prior.engineersAvailable} last week`, status: 'Red', tone: 'red' },
    { label: 'Monthly local cost', value: money(cost.review), plan: `Plan ${money(cost.plan)} · prior ${money(cost.prior)}`, delta: `${money(cost.review - cost.plan)} above plan (+${Math.round((cost.review / cost.plan - 1) * 100)}%)`, status: 'Review variance', tone: 'amber' },
    { label: '13-week cash headroom', value: money(REVIEW_HEADROOM), plan: 'Above $500k minimum cash floor', delta: 'Assumed 13-week minimum · Finance review 08 Sep', status: 'Monitor receipts', tone: 'amber' },
  ];
  return <>
    <div className="md-period"><span>Monthly review · {month.period}</span><span>Finance: {month.updated} · operations: {week.updated}</span></div>
    <p className="md-example-note">Illustrative case, not Shield operating records. Decisions and thresholds below are proposed. All figures and operating statuses use the documented planning assumptions.</p>
    <section aria-labelledby="md-decisions-heading"><div className="md-section-title"><h2 id="md-decisions-heading">Decisions required this month</h2><span>MD review · 07 Sep 2026 · 3 requests</span></div>
      <div className="md-decision-cards">{decisions.map(d => <article className="panel md-decision-card" key={d.id}><span className="md-card-meta">{d.id} · Decide by {d.due}</span><h3>{d.title}</h3><p>{d.recommendation}</p><details><summary>Trade-off & closure</summary><p>{d.tradeoff}</p><p>{d.closure}</p></details><footer>Accountable: {d.owner}</footer></article>)}</div>
    </section>
    <section aria-label="Monthly operating KPIs"><div className="md-section-title"><h2>Monthly operating scorecard</h2><span>Plan → forecast → intervention</span></div><div className="md-kpis">{kpis.map(k => <article className="panel md-kpi" key={k.label}><span className="md-kpi-label">{k.label}<span className={k.tone}>{k.status}</span></span><strong className="md-actual">{k.value}</strong><p className="md-kpi-plan">{k.plan}</p><span className={`md-metric-context ${k.tone}`}>{k.delta}</span></article>)}</div>
      <div className="md-table-wrap panel"><table className="md-deals"><thead><tr>{['Financial KPI · USD', 'August', 'Plan', 'July', 'Forward view / action'].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{month.rows.filter(r => ['Revenue', 'New bookings', 'Collections'].includes(r.label)).map(r => <tr key={r.label}><th scope="row">{r.label}<small>{r.owner}</small></th><td>{money(r.review)}</td><td>{money(r.plan)}</td><td>{money(r.prior)}</td><td>{r.label === 'Revenue' ? 'Assumed $800k accepted integration / support scope; next $4M milestone forecast 14 Oct.' : r.label === 'Collections' ? 'Assume $720k August receipts and $2.2M over the next 13 weeks; Finance to phase receipts by 08 Sep.' : 'Assume $1.5M incremental integration / support bookings; BD to review next paid scope by 11 Sep.'}</td></tr>)}</tbody></table></div>
      <p className="md-footnote">Monthly figures assume accepted integration and support work, incremental orders and related receipts. See Assumptions for values and calculation basis.</p>
    </section>
    <section aria-labelledby="md-triggers-heading"><div className="md-section-title"><h2 id="md-triggers-heading">Early warnings & escalation</h2><span>Proposed thresholds · do not wait for month-end</span></div><div className="md-table-wrap panel"><table className="md-deals"><thead><tr>{['Area', 'Current signal', 'Escalation trigger', 'Owner / response'].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{triggers.map(row => <tr key={row[0]}><th scope="row">{row[0]}</th>{row.slice(1).map((v, i) => <td key={i}>{v}</td>)}</tr>)}</tbody></table></div></section>
    <section aria-labelledby="md-followthrough-heading"><div className="md-section-title"><h2 id="md-followthrough-heading">Decision follow-through</h2><span>Closure requires evidence</span></div><div className="panel md-followthrough"><strong>{week.actions} open actions · {prior.actions} in prior snapshot</strong><p>The count fell, but acceptance slipped another {week.lateDays - prior.lateDays} days. Assume 2 prior actions closed and 1 new recovery action opened; 1 of the 3 open actions is overdue.</p><p>Assumed owners / due dates: Finance cash phasing · 08 Sep; Programme recovery · 09 Sep; Industrialisation sign-off · 11 Sep. Chief of Staff reviews the overdue recovery action on 07 Sep.</p><details><summary>Decision history · assumed</summary><p>Assumed closures: staffing review · People lead · 02 Sep · roster confirmed at 9 engineers; JSW delivery review · Industrialisation lead · 03 Sep · delivery sequence agreed. Acceptance still slipped 7 days, prompting D01. D01–D03 are pending planning requests.</p></details></div></section>
  </>;
}
