import { MONTHLY_REVIEWS, WEEKLY_REVIEWS } from '@/data/md-reviews';

const decisions = [
  { id: 'D01', title: 'Prioritise Army recovery', due: '07 Sep', owner: 'Programme lead', recommendation: 'Reserve India engineering for acceptance; request temporary HQ support before starting OEM integration.', tradeoff: 'OEM discovery can continue, but integration waits. Extra support has a cost; recovery benefit remains unverified.', closure: 'By 09 Sep: named staffing plan and a customer-aligned recovery forecast. MD decides allocation; HQ approves its support.' },
  { id: 'D02', title: 'Gate new supplier commitments', due: '07 Sep · before commitment', owner: 'Finance lead', recommendation: 'Require a reconciled 13-week cash forecast and confirmed funding before new discretionary supplier commitments.', tradeoff: 'May defer procurement. Proceeding without evidence could create an unfunded obligation; existing commitments remain in the forecast.', closure: 'By 08 Sep: opening cash, dated receipts/outflows and funding confirmation. Escalate funding beyond India authority to HQ Treasury.' },
  { id: 'D03', title: 'Require production-readiness evidence', due: '09 Sep · before order release', owner: 'Industrialisation lead', recommendation: 'Keep new production order releases gated until JSW readiness evidence is reviewed.', tradeoff: 'May shift the release date; an announced target alone does not establish readiness.', closure: 'By 11 Sep: signed gate checklist, open dependencies and a dated recovery plan. MD resolves partner escalation; technical sign-off stays with the gate owner.' },
];
const triggers = [
  ['Delivery / capacity', 'Red · acceptance +14 days; 5 engineers uncovered', 'Forecast slips >7 days, or a critical role remains unassigned 14 days before its gate.', 'Programme lead → MD within 24h; recovery plan due 09 Sep.'],
  ['Cash', 'Unverified · no reconciled cash baseline', 'Any week below the approved cash floor, or a commitment falls due before confirmed funding.', 'Finance lead → MD / HQ Treasury before commitment; evidence due 08 Sep.'],
  ['Readiness / approvals', 'Unverified · production gate evidence missing', 'A required sign-off is missing at release, or approval lead time exceeds time remaining.', 'Industrialisation lead → MD / gate owner immediately; hold affected release; evidence due 11 Sep.'],
  ['Data / decisions', 'Evidence required · no closure record supplied', 'An action misses its due date, or a critical source misses its agreed refresh.', 'Chief of Staff → accountable owner same day; flag to MD if unresolved in 24h.'],
];

export default function MdMonthlyReview() {
  const week = WEEKLY_REVIEWS[0], prior = WEEKLY_REVIEWS[1], month = MONTHLY_REVIEWS[0];
  const cost = month.rows.find(row => row.label === 'Local operating cost')!;
  const gap = week.engineersNeeded - week.engineersAvailable;
  const money = (n: number) => `$${Math.round(n * 1000).toLocaleString('en-US')}k`;
  const kpis = [
    { label: 'Acceptance forecast', value: week.forecastAcceptance, plan: `Committed ${week.plannedAcceptance}`, delta: `${week.lateDays} days late · +${week.lateDays - prior.lateDays} days vs prior week`, status: 'Red', tone: 'red' },
    { label: 'Engineering coverage', value: `${week.engineersAvailable} / ${week.engineersNeeded}`, plan: `${gap} engineers uncovered`, delta: `Gap was ${prior.engineersNeeded - prior.engineersAvailable} last week`, status: 'Red', tone: 'red' },
    { label: 'Monthly local cost', value: money(cost.review), plan: `Plan ${money(cost.plan)} · prior ${money(cost.prior)}`, delta: `${money(cost.review - cost.plan)} above plan (+${Math.round((cost.review / cost.plan - 1) * 100)}%)`, status: 'Review variance', tone: 'amber' },
    { label: '13-week cash headroom', value: 'Unverified', plan: 'Opening cash / funding not supplied', delta: 'Finance evidence due 08 Sep', status: 'Unknown', tone: 'amber' },
  ];
  return <>
    <div className="md-period"><span>Monthly review · {month.period}</span><span>Finance: {month.updated} · operations: {week.updated}</span></div>
    <p className="md-example-note">Illustrative case, not Shield operating records. Decisions and thresholds below are proposed. Snapshot dates are fixed; missing or stale evidence is never green.</p>
    <section aria-labelledby="md-decisions-heading"><div className="md-section-title"><h2 id="md-decisions-heading">Decisions required this month</h2><span>MD review · 07 Sep 2026 · 3 requests</span></div>
      <div className="md-decision-cards">{decisions.map(d => <article className="panel md-decision-card" key={d.id}><span className="md-card-meta">{d.id} · Decide by {d.due}</span><h3>{d.title}</h3><p>{d.recommendation}</p><details><summary>Trade-off & closure</summary><p>{d.tradeoff}</p><p>{d.closure}</p></details><footer>Accountable: {d.owner}</footer></article>)}</div>
    </section>
    <section aria-label="Monthly operating KPIs"><div className="md-section-title"><h2>Monthly operating scorecard</h2><span>Plan → forecast → intervention</span></div><div className="md-kpis">{kpis.map(k => <article className="panel md-kpi" key={k.label}><span className="md-kpi-label">{k.label}<span className={k.tone}>{k.status}</span></span><strong className="md-actual">{k.value}</strong><p className="md-kpi-plan">{k.plan}</p><span className={`md-metric-context ${k.tone}`}>{k.delta}</span></article>)}</div>
      <div className="md-table-wrap panel"><table className="md-deals"><thead><tr>{['Financial KPI · USD', 'August', 'Plan', 'July', 'Forward view / action'].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{month.rows.filter(r => ['Revenue', 'New bookings', 'Collections'].includes(r.label)).map(r => <tr key={r.label}><th scope="row">{r.label}<small>{r.owner}</small></th><td>{money(r.review)}</td><td>{money(r.plan)}</td><td>{money(r.prior)}</td><td>{r.label === 'Revenue' ? 'Illustrative $4M acceptance milestone now forecast 14 Oct; validate recognition with Finance.' : r.label === 'Collections' ? 'Receipt forecast unverified; reconcile invoice prerequisites and payment dates by 08 Sep.' : 'No evidenced stage advance in Navy / OEM routes. BD to validate sponsor and funded scope by 11 Sep.'}</td></tr>)}</tbody></table></div>
      <p className="md-footnote">Zero against zero plan does not establish health. The next acceptance gate, receipt evidence and customer progress determine intervention.</p>
    </section>
    <section aria-labelledby="md-triggers-heading"><div className="md-section-title"><h2 id="md-triggers-heading">Early warnings & escalation</h2><span>Proposed thresholds · do not wait for month-end</span></div><div className="md-table-wrap panel"><table className="md-deals"><thead><tr>{['Area', 'Current signal', 'Escalation trigger', 'Owner / response'].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{triggers.map(row => <tr key={row[0]}><th scope="row">{row[0]}</th>{row.slice(1).map((v, i) => <td key={i}>{v}</td>)}</tr>)}</tbody></table></div></section>
    <section aria-labelledby="md-followthrough-heading"><div className="md-section-title"><h2 id="md-followthrough-heading">Decision follow-through</h2><span>Closure requires evidence</span></div><div className="panel md-followthrough"><strong>{week.actions} open actions · {prior.actions} in prior snapshot</strong><p>The count fell, but acceptance slipped another {week.lateDays - prior.lateDays} days. Recovery effectiveness is unverified. Action-level owners, due dates and closure evidence were not supplied.</p><p>Chief of Staff · reconcile the existing action log by 08 Sep. Show overdue or ineffective interventions here; keep completed records in the history.</p><details><summary>Decision history · evidence needed</summary><p>No decision-level history is supplied in this case. Record each decision once: date, choice and rationale, accountable person, due date, closure evidence and resulting forecast. D01–D03 above are pending requests, not approved decisions.</p></details></div></section>
  </>;
}
