import { useState } from 'react';
import MdFunctionalKpis from './MdFunctionalKpis';
import { CONTRACTS, ENGINEERING_WORK, ENGAGEMENTS, MD_DECISIONS, NEXT_PAYMENTS, PAYMENTS, PORTFOLIO_DATE, PORTFOLIO_TOTALS as totals, PROGRAMME_PORTFOLIO, TRIAL_CAMPAIGNS, dateLabel, daysUntil, money } from '@/data/md-portfolio';

const VIEWS = ['MD priorities', 'Function KPIs', 'Programmes', 'Engineering & trials', 'Contracts & payments', 'Engagement calendar'] as const;
type View = typeof VIEWS[number];
const Title = ({ title, note }: { title: string; note: string }) => <div className="md-section-title"><h2>{title}</h2><span>{note}</span></div>;

export default function MdPortfolio() {
  const [view, setView] = useState<View>('MD priorities');
  const [programme, setProgramme] = useState('all');
  const [horizon, setHorizon] = useState('all');
  const openProgramme = (id: string) => { setProgramme(id); setView('Programmes'); };
  const selected = PROGRAMME_PORTFOLIO.filter(p => programme === 'all' || p.id === programme);
  const payments = PAYMENTS.filter(p => (programme === 'all' || p.programme === programme) && (horizon === 'all' || (p.status !== 'Received' && daysUntil(p.due) >= 0 && daysUntil(p.due) <= Number(horizon))));
  const meetings = ENGAGEMENTS.filter(e => programme === 'all' || e.programme === programme);
  const contracts = CONTRACTS.filter(c => programme === 'all' || c.id === programme);
  return <div className="md-portfolio">
    <div className="md-period"><span>MD review · {dateLabel(PORTFOLIO_DATE)}</span><span>Next 30 days → 6 / 12 months → contract life</span></div>
    <p className="md-example-note">Illustrative operating case · programme dates, financials and staffing are assumed. Open Assumptions for the basis and responsibility split.</p>
    <div className="md-kpis">
      {[
        ['Assumed contracts', money(totals.contracts), `${CONTRACTS.length} contracts across Shield entities`, 'Contracts & payments'],
        ['Receipts in next 90 days', money(totals.nextCash), 'Army + JSW · both depend on acceptance', 'Contracts & payments'],
        ['Engineering assigned / needed', `${totals.assigned} / ${totals.required}`, `${totals.required - totals.assigned} additional engineers to allocate`, 'Engineering & trials'],
        ['Government pursuits', money(totals.pursuit), 'Capital + urgent pilot · outside contract total', 'Programmes'],
      ].map(([label, value, note, target]) => <button key={label} className="panel md-kpi" onClick={() => { setProgramme('all'); setHorizon(label === 'Receipts in next 90 days' ? '90' : 'all'); setView(target as View); }}><span className="md-kpi-label">{label}<span aria-hidden="true">↗</span></span><strong className="md-actual">{value}</strong><span className="md-metric-context">{note}</span></button>)}
    </div>
    <div className="md-portfolio-controls">
      <div className="md-portfolio-nav" role="group" aria-label="Dashboard views">{VIEWS.map(v => <button key={v} aria-pressed={view === v} onClick={() => setView(v)}>{v}</button>)}</div>
      {view !== 'MD priorities' && view !== 'Function KPIs' && <label>Programme<select aria-label="Filter dashboard programme" value={programme} onChange={e => setProgramme(e.target.value)}><option value="all">All programmes</option>{PROGRAMME_PORTFOLIO.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
    </div>
    <div className="md-portfolio-view" aria-label={view}>
      {view === 'MD priorities' && <>
        <section><Title title="The decisions only the MD can make" note="Owner · deadline · consequence · closure" />
          <div className="md-portfolio-decisions">{MD_DECISIONS.map(d => <article className="panel md-decision-card" key={d.id}><span className="md-card-meta">{d.id} · by {dateLabel(d.due)}</span><h3>{d.title}</h3><p>{d.request}</p><p className="md-consequence">{d.consequence}</p><details><summary>Required follow-through</summary><p>{d.closure}</p></details><footer>{d.owner}<button onClick={() => openProgramme(d.programme)}>Programme ↗</button></footer></article>)}</div>
        </section>
        <section><Title title="Commitments that can move the business" note="Customer dates and product dependencies" />
          <div className="panel md-portfolio-watch">{PROGRAMME_PORTFOLIO.filter(p => ['army', 'oem', 'jsw', 'japan', 'poland'].includes(p.id)).map(p => <button key={p.id} onClick={() => openProgramme(p.id)}><span><strong>{p.name}</strong><small>{p.owner}</small></span><span><b className={p.tone}>{p.status}</b><small>{p.forecast}</small></span><span>{p.action}<small>{p.impact}</small></span><span aria-hidden="true">↗</span></button>)}</div>
        </section>
        <div className="md-portfolio-pair"><section className="panel md-portfolio-brief"><Title title="Cash follows acceptance" note="Next 90 days" />{NEXT_PAYMENTS.map(p => <div key={p.invoice}><strong>{money(p.amount)} · {p.contract}</strong><p>{dateLabel(p.due)} · {p.trigger}</p></div>)}<p className="md-footnote">Receipts belong to the contracting entity. India’s assumed operating envelope is $660k; HQ allocation requires its own decision.</p></section>
          <section className="panel md-portfolio-brief"><Title title="Where the MD needs to be" note="Next customer and partner conversations" />{ENGAGEMENTS.slice(0, 3).map(e => <div key={e.meeting}><strong>{dateLabel(e.date)} · {e.meeting}</strong><p>{e.purpose}</p></div>)}<button onClick={() => { setProgramme('all'); setView('Engagement calendar'); }}>Open full calendar ↗</button></section></div>
      </>}
      {view === 'Function KPIs' && <MdFunctionalKpis />}
      {view === 'Programmes' && <>
        <section><Title title="Programme commitments" note={`${selected.length} in view · all statuses are scenario assumptions`} /><div className="md-programme-grid">{selected.map(p => <article key={p.id} className="panel md-programme-card"><div className="md-programme-eyebrow"><span>{p.lane}</span><b className={p.tone}>{p.status}</b></div><h3>{p.name}</h3><p>{p.outcome}</p><dl><div><dt>Commercial position</dt><dd>{money(p.value)} · {p.stage}</dd></div><div><dt>Customer / partner commitment</dt><dd>{p.commitment}</dd></div><div><dt>Current forecast</dt><dd>{p.forecast}</dd></div><div><dt>Next gate</dt><dd>{p.next}</dd></div><div><dt>Shared dependency</dt><dd>{p.dependency}</dd></div><div><dt>Contract / payment consequence</dt><dd>{p.impact}</dd></div></dl><footer><strong>{p.owner}</strong><span>{p.action}</span></footer><details><summary>Six- and twelve-month outlook</summary><p>{p.six}</p><p>{p.twelve}</p></details></article>)}</div></section>
        {(programme === 'all' || programme === 'maritime' || programme === 'urgent') && <section className="panel md-portfolio-brief"><Title title="Maritime: two buying routes, distinct gates" note="Planning baseline · 01 Sep 2026" /><ol className="md-acquisition-stages">{['AoN planning baseline', 'RFP issued', 'Bid & clarifications', 'Evaluation & negotiation', 'Award & delivery'].map((s, i) => <li key={s}><span>{i + 1}</span>{s}</li>)}</ol><div className="md-portfolio-pair"><div><h3>Six-month RFP case</h3><p>01 Mar 2027 RFP target → 15 Mar pre-bid meeting → 30 Apr bid submission → Sep technical evaluation. Work backwards to partner scope, demonstration capacity, pricing and licence terms.</p></div><div><h3>Twelve-month RFP case</h3><p>01 Sep 2027 RFP target → 15 Sep pre-bid → 31 Oct bid submission. Review the $120k bid envelope quarterly; avoid holding scarce engineers idle.</p></div></div><p>Urgent pilot: separate $1.2M opportunity → customer funding decision 30 Oct 2026 → assumed pilot delivery 15 Jan 2027 if awarded. Confirm scope and buying authority before promising an asset.</p><p className="md-footnote">Six / twelve months are planning cases, not universal AoN validity rules. Procurement basis: <a href="https://www.ddpmod.gov.in/sites/default/files/DAP%202020%20%2011%20Nov%2021_0.pdf" target="_blank" rel="noreferrer">MoD DAP 2020</a>; the applicable route and tender govern the case.</p></section>}
      </>}
      {view === 'Engineering & trials' && <>
        <section><Title title="One resource plan for India and global programmes" note={`${totals.assigned} assigned · ${totals.required} required · ${totals.required - totals.assigned} additional engineers`} /><div className="md-table-wrap panel"><table className="md-deals"><thead><tr>{['Workstream', 'Assigned / required', 'India commitment', 'Global / partner commitment', 'MD intervention'].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{ENGINEERING_WORK.filter(w => programme === 'all' || w.id === programme || (programme === 'army' && w.id === 'sdk')).map(w => <tr key={w.id}><th scope="row">{w.name}</th><td><strong>{w.assigned} / {w.required}</strong><progress aria-label={`${w.name} staffing coverage`} value={w.assigned} max={w.required} /></td><td>{w.deliverable}</td><td>{w.global}</td><td>{w.risk}</td></tr>)}</tbody></table>{!ENGINEERING_WORK.some(w => programme === 'all' || w.id === programme) && <p className="md-empty">Pursuit engineering is not yet allocated. Confirm a paid scope or bid decision before reserving the team.</p>}</div></section>
        {(programme === 'all' || programme === 'army') && <section><Title title="Army field trials & SDK learning" note="18 / 24 flights complete · 15 evidence reports accepted" /><div className="md-trial-grid">{TRIAL_CAMPAIGNS.map(t => <article className="panel md-portfolio-brief" key={t.terrain}><h3>{t.terrain}</h3><strong className="md-actual">{t.completed} / {t.planned}</strong><p>Flights complete · {t.accepted} reports accepted</p><progress aria-label={`${t.terrain} flight campaign`} value={t.completed} max={t.planned} /><p>{t.result}</p><p>{t.next}</p><small>{t.owner}</small></article>)}</div><div className="panel md-portfolio-brief"><h3>Flight → evidence review → SDK finding → HQ product decision → next campaign</h3><p>Field Test lead owns the campaign record; India Engineering owns the SDK evaluation pack due 30 Sep. HQ Product reviews reusable findings on 09 Oct. Protect 2 engineers for SDK and research, and distinguish a completed flight from customer-accepted evidence.</p></div></section>}
        <section className="panel md-portfolio-brief"><Title title="Product commitments in both directions" note="India Engineering + HQ Product · weekly" /><div className="md-portfolio-pair"><div><h3>HQ owes India</h3><p>18 Sep · JSW transfer documentation. 25 Sep · Army / Poland release candidate. 16 Sep · additional staffing decision for Army, OEM, Japan and Poland.</p></div><div><h3>India owes global programmes</h3><p>30 Sep · Army SDK evaluation pack. 09 Oct · reusable research findings. 30 Nov · Japan integration package. 15 Dec · Poland validation report.</p></div></div></section>
      </>}
      {view === 'Contracts & payments' && <>
        <section><Title title="Contract life, licence rights and cash gates" note="Assumed executed portfolio · each contract counted once" /><div className="md-table-wrap panel"><table className="md-deals"><thead><tr>{['Contract / term', 'Full value', 'Contracting boundary', 'Licence economics', 'Renewal / expansion gate'].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{contracts.map(c => <tr key={c.id}><th scope="row">{c.name}<small>{c.period}</small></th><td>{money(c.value)}</td><td>{c.entity}</td><td>{c.licence}</td><td>{c.renewal}</td></tr>)}</tbody></table>{!contracts.length && <p className="md-empty">This is a pursuit. It has no executed contract in the assumed portfolio; price, award and payment terms remain a future commercial gate.</p>}</div><p className="md-footnote">Licence components are included in contract totals. Unit royalties, optional renewals and pursuit values are additional opportunities, excluded from the executed portfolio.</p></section>
        <section><div className="md-section-title"><h2>Payment milestones & invoice readiness</h2><label className="md-payment-filter">Window<select aria-label="Payment window" value={horizon} onChange={e => setHorizon(e.target.value)}><option value="all">Full contract life</option><option value="90">Next 90 days</option><option value="365">Next 12 months</option></select></label></div><div className="md-table-wrap panel"><table className="md-deals"><thead><tr>{['Due / forecast', 'Contract', 'Receipt', 'State', 'Acceptance / invoice dependency'].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{payments.slice().sort((a, b) => a.due.localeCompare(b.due)).map(p => <tr key={p.invoice}><th scope="row">{dateLabel(p.due)}</th><td>{p.contract}</td><td>{money(p.amount)}</td><td><span className={p.status === 'At risk' ? 'amber' : p.status === 'Received' ? 'green' : ''}>{p.status}</span></td><td>{p.trigger}<small>{p.invoice}</small></td></tr>)}</tbody></table>{!payments.length && <p className="md-empty">No payment falls in this selection. Choose the full contract life to inspect later milestones.</p>}</div></section>
        <div className="panel md-portfolio-brief"><Title title="Keep programme receipts and India spending distinct" note="Finance + HQ Treasury" /><p>Portfolio receipts to date: {money(totals.received)}. Remaining contract receipts: {money(totals.contracts - totals.received)}. Next 90 days: {money(totals.nextCash)}, dependent on Army and JSW acceptance.</p><p>India operating allocation: $660k for 13 weeks, including the $45k Army recovery allowance, first $30k maritime bid tranche and $33k September–October engagement budget. Finance owns weekly spending and HQ funding transfers; customer receipts at HQ are not automatically India cash.</p></div>
      </>}
      {view === 'Engagement calendar' && <section><Title title="Meetings that advance a programme" note="Proposed calendar · preparation and follow-through" /><div className="md-engagement-list">{meetings.map(e => <article className="panel md-engagement" key={e.meeting}><div className="md-engagement-date"><strong>{dateLabel(e.date)}</strong><span>{money(e.budget)} budget</span></div><div><h3>{e.meeting}</h3><p>{e.people}</p><strong>{e.purpose}</strong><details><summary>Preparation & next action</summary><p>Prepare: {e.preparation}</p><p>Follow-up: {e.followup}</p></details></div><button onClick={() => openProgramme(e.programme)}>Programme ↗</button></article>)}</div>{!meetings.length && <p className="md-empty">Coordinate this programme through the global product review on 16 Sep; add a dedicated customer review when its date is agreed.</p>}<p className="md-footnote">Conference, lunches, dinner and customer meetings are assumed planning entries. Progress is a documented next gate, owner and date.</p></section>}
    </div>
  </div>;
}
